name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Define docker image tag
    strategy:
      matrix:
        include:
          - branch: master
            image_tag: latest
          - branch: develop
            image_tag: dev

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # 3. Build
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --verbosity normal

      # 4. DockerHub login
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Docker Image Build and Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simpleapi:${{ matrix.image_tag }}

  deploy:
    name: Deploy to server
    runs-on: self-hosted
    needs: build 

    strategy:
      matrix:
        include:
          - branch: master
            image_tag: latest
          - branch: develop 
            image_tag: dev

    steps:
      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simpleapi:${{ matrix.image_tag }}

      - name: Stop old container
        run: docker stop simpleapi || true

      - name: Remove old container
        run: docker rm simpleapi || true

      - name: Run new container
        run: docker run -d --name simpleapi -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/simpleapi:${{ matrix.image_tag }}
